/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'RemboL' at '1/2/17 5:15 PM' with Gradle 2.13
 *
 * @author RemboL, @date 1/2/17 5:15 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
